// This is auto-generated by Nexus-UX. DO NOT EDIT.

namespace AereaCo.NexusUX.FSharp

open System

type FragmentMergeMode =
/// Morphs the fragment into the existing element using idiomorph.
| Morph
/// Replaces the inner HTML of the existing element.
| Inner
/// Replaces the outer HTML of the existing element.
| Outer
/// Prepends the fragment to the existing element.
| Prepend
/// Appends the fragment to the existing element.
| Append
/// Inserts the fragment before the existing element.
| Before
/// Inserts the fragment after the existing element.
| After
/// Upserts the attributes of the existing element.
| UpsertAttributes

type EventType =
/// An event for merging HTML fragments into the DOM.
| MergeFragments
/// An event for merging signals.
| MergeSignals
/// An event for removing HTML fragments from the DOM.
| RemoveFragments
/// An event for removing signals.
| RemoveSignals
/// An event for executing &lt;script/&gt; elements in the browser.
| ExecuteScript
/// An event for patching elements.
| PatchElements
/// An event for patching signals.
| PatchSignals


module Consts =
    let [<Literal>] StateKey               = "state"
    let [<Literal>] Version                   = "0.0.1-alpha"

    /// Default: TimeSpan.FromMilliseconds 1000
    let DefaultSseRetryDuration = TimeSpan.FromMilliseconds 1000


    /// Default: morph - Morphs the fragment into the existing element using idiomorph.
    let DefaultFragmentMergeMode = FragmentMergeMode::Morph

    let [<Literal>] DefaultFragmentsUseViewTransitions = false
    let [<Literal>] DefaultMergeSignalsOnlyIfMissing = false
    let [<Literal>] DefaultExecuteScriptAutoRemove = true

    let [<Literal>] DefaultExecuteScriptAttributes = "type module"

    let [<Literal>] StateDatalineSelector = "selector"
    let [<Literal>] StateDatalineMergeMode = "mergeMode"
    let [<Literal>] StateDatalineFragments = "fragments"
    let [<Literal>] StateDatalineUseViewTransition = "useViewTransition"
    let [<Literal>] StateDatalineSignals = "signals"
    let [<Literal>] StateDatalineOnlyIfMissing = "onlyIfMissing"
    let [<Literal>] StateDatalinePaths = "paths"
    let [<Literal>] StateDatalineScript = "script"
    let [<Literal>] StateDatalineAttributes = "attributes"
    let [<Literal>] StateDatalineAutoRemove = "autoRemove"

    module FragmentMergeMode =
        let toString this =
            match this with
                | FragmentMergeMode.Morph -> "morph"
                | FragmentMergeMode.Inner -> "inner"
                | FragmentMergeMode.Outer -> "outer"
                | FragmentMergeMode.Prepend -> "prepend"
                | FragmentMergeMode.Append -> "append"
                | FragmentMergeMode.Before -> "before"
                | FragmentMergeMode.After -> "after"
                | FragmentMergeMode.UpsertAttributes -> "upsertAttributes"

    module EventType =
        let toString this =
            match this with
                | EventType.MergeFragments -> "state-merge-fragments"
                | EventType.MergeSignals -> "state-merge-signals"
                | EventType.RemoveFragments -> "state-remove-fragments"
                | EventType.RemoveSignals -> "state-remove-signals"
                | EventType.ExecuteScript -> "state-execute-script"
                | EventType.PatchElements -> "patch-elements"
                | EventType.PatchSignals -> "patch-signals"