// This is auto-generated by Nexus-UX. DO NOT EDIT.

namespace AereaCo.NexusUX;

using System;

public enum FragmentMergeMode
{
    /// Morphs the fragment into the existing element using idiomorph.
    Morph,
    /// Replaces the inner HTML of the existing element.
    Inner,
    /// Replaces the outer HTML of the existing element.
    Outer,
    /// Prepends the fragment to the existing element.
    Prepend,
    /// Appends the fragment to the existing element.
    Append,
    /// Inserts the fragment before the existing element.
    Before,
    /// Inserts the fragment after the existing element.
    After,
    /// Upserts the attributes of the existing element.
    UpsertAttributes,

}
public enum EventType
{
    /// An event for merging HTML fragments into the DOM.
    MergeFragments,
    /// An event for merging signals.
    MergeSignals,
    /// An event for removing HTML fragments from the DOM.
    RemoveFragments,
    /// An event for removing signals.
    RemoveSignals,
    /// An event for executing &lt;script/&gt; elements in the browser.
    ExecuteScript,
    /// An event for patching elements.
    PatchElements,
    /// An event for patching signals.
    PatchSignals,

}

public static class Consts
{
    public const string StateKey = "state";
    public const string Version     = "0.0.1-alpha";

    /// Default: TimeSpan.FromMilliseconds 1000
    public static readonly TimeSpan DefaultSseRetryDuration = TimeSpan.FromMilliseconds(1000);


    /// Default: morph - Morphs the fragment into the existing element using idiomorph.
    public const FragmentMergeMode DefaultFragmentMergeMode = FragmentMergeMode.Morph;

    public const bool DefaultFragmentsUseViewTransitions = false;
    public const bool DefaultMergeSignalsOnlyIfMissing = false;
    public const bool DefaultExecuteScriptAutoRemove = true;

    public const string DefaultExecuteScriptAttributes = "type module";

    public const string StateDatalineSelector = "selector";
    public const string StateDatalineMergeMode = "mergeMode";
    public const string StateDatalineFragments = "fragments";
    public const string StateDatalineUseViewTransition = "useViewTransition";
    public const string StateDatalineSignals = "signals";
    public const string StateDatalineOnlyIfMissing = "onlyIfMissing";
    public const string StateDatalinePaths = "paths";
    public const string StateDatalineScript = "script";
    public const string StateDatalineAttributes = "attributes";
    public const string StateDatalineAutoRemove = "autoRemove";

    public static string EnumToString( FragmentMergeMode enumValue ) => enumValue switch {
        FragmentMergeMode.Morph => "morph",
        FragmentMergeMode.Inner => "inner",
        FragmentMergeMode.Outer => "outer",
        FragmentMergeMode.Prepend => "prepend",
        FragmentMergeMode.Append => "append",
        FragmentMergeMode.Before => "before",
        FragmentMergeMode.After => "after",
        FragmentMergeMode.UpsertAttributes => "upsertAttributes",
        _ => throw new NotImplementedException($"FragmentMergeMode.{enumValue}")
    };
    public static string EnumToString( EventType enumValue ) => enumValue switch {
        EventType.MergeFragments => "state-merge-fragments",
        EventType.MergeSignals => "state-merge-signals",
        EventType.RemoveFragments => "state-remove-fragments",
        EventType.RemoveSignals => "state-remove-signals",
        EventType.ExecuteScript => "state-execute-script",
        EventType.PatchElements => "patch-elements",
        EventType.PatchSignals => "patch-signals",
        _ => throw new NotImplementedException($"EventType.{enumValue}")
    };
}