<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>AereaCo.NexusUX</AssemblyName>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>AereaCo.NexusUX</RootNamespace>
        <Version>1.0.0-beta.6</Version>
        <Title>AereaCo.NexusUX</Title>
        <Authors>Greg Holden and contributors</Authors>
        <Description>SDK for ServerSentEvents and convenience methods for Nexus-UX</Description>
        <PackageProjectUrl>https://github.com/aereaco/nexus-ux</PackageProjectUrl>
        <PackageIcon>nexus-ux_icon.png</PackageIcon>
        <RepositoryUrl>https://github.com/aereaco/nexus-ux</RepositoryUrl>
        <PackageTags>nexus-ux;nexus-ux-sharp;asp.net core;asp.net;.net core;routing;web;csharp</PackageTags>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\..\fsharp\src\AereaCo.NexusUX.FSharp.fsproj" />
    </ItemGroup>
    
    <ItemGroup>
      <None Include="..\..\assets\nexus-ux_icon.png">
        <Pack>True</Pack>
        <PackagePath></PackagePath>
        <Link>nexus-ux_icon.png</Link>
      </None>
    </ItemGroup>

</Project>