<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://www.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>nexus-ux-java-sdk-jaxrs</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>
    <parent>
        <groupId>dev.nexus-ux</groupId>
        <artifactId>nexus-ux-java-sdk-suite</artifactId>
        <version>1.0.0</version>
    </parent>

    <name>Nexus-UX Java SDK JAX-RS plugin </name>
    <description>JAX-RS plugin for the Nexus-UX SDK</description>

    <properties>
        <jakarta.ws-rs-api.version>4.0.0</jakarta.ws-rs-api.version>
        <jakarta.servlet.api.version>6.1.0</jakarta.servlet.api.version>
    </properties>

    <distributionManagement>
        <repository>
            <id>github</id>
            <url>https://maven.pkg.github.com/aereaco/nexus-ux</url>
        </repository>
    </distributionManagement>

    <dependencies>
        <!-- Servlet API -->
        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
            <version>${jakarta.ws-rs-api.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <version>${jakarta.servlet.api.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>dev.nexus-ux</groupId>
            <artifactId>nexus-ux-java-sdk-core</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>