# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in nexus_ux.gemspec
gemspec

gem 'rake', '~> 13.0'

gem 'rspec', '~> 3.0'

gem 'debug'

group :test do
  # Async to test NexusUX::AsyncExecutor
  gem 'async'
  # Puma to host test server
  gem 'puma'
end