<?php

namespace aereaco\nexusux\enums;

/**
 * This is auto-generated by Nexus-UX. DO NOT EDIT.
 */
enum EventType: string
{

    // An event for merging HTML fragments into the DOM.
    case MergeFragments = 'state-merge-fragments';

    // An event for merging signals.
    case MergeSignals = 'state-merge-signals';

    // An event for removing HTML fragments from the DOM.
    case RemoveFragments = 'state-remove-fragments';

    // An event for removing signals.
    case RemoveSignals = 'state-remove-signals';

    // An event for executing &lt;script/&gt; elements in the browser.
    case ExecuteScript = 'state-execute-script';

    // An event for patching elements.
    case PatchElements = 'patch-elements';

    // An event for patching signals.
    case PatchSignals = 'patch-signals';
}