package aereaco.nexusux.enums;

/**
 * This is auto-generated by Nexus-UX. DO NOT EDIT.
 */
public enum EventType {

    // An event for merging HTML fragments into the DOM.
    MergeFragments("state-merge-fragments"),

    // An event for merging signals.
    MergeSignals("state-merge-signals"),

    // An event for removing HTML fragments from the DOM.
    RemoveFragments("state-remove-fragments"),

    // An event for removing signals.
    RemoveSignals("state-remove-signals"),

    // An event for executing &lt;script/&gt; elements in the browser.
    ExecuteScript("state-execute-script"),

    // An event for patching elements.
    PatchElements("patch-elements"),

    // An event for patching signals.
    PatchSignals("patch-signals");

    private final String value;

    EventType(String value) {
        this.value = value;
    }
    
    @Override
    public String toString() {
        return value;
    }
}